
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: mate-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
